package com.fooddelivery.order.mapper;

import com.fooddelivery.order.dto.CreateOrderItemDto;
import com.fooddelivery.order.dto.CreateOrderRequestDto;
import com.fooddelivery.order.dto.OrderResponse;
import com.fooddelivery.order.dto.external.OutletDto;
import com.fooddelivery.order.entity.DeliveryAddressSnapshot;
import com.fooddelivery.order.entity.Order;
import com.fooddelivery.order.entity.OrderItem;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Component
public class OrderMapper {

    public Order createOrder(CreateOrderRequestDto request, OutletDto outlet) {
        Order order = new Order();
        // orderId is auto-generated by field initializer
        order.setOrderNumber(generateOrderNumber());

        // Convert incoming String IDs to UUIDs expected by the entity
        try {
            order.setUserId(UUID.fromString(request.getUserId()).toString());
        } catch (Exception ex) {
            throw new RuntimeException("Invalid UUID for userId: " + request.getUserId());
        }
        try {
            order.setOutletId(UUID.fromString(request.getOutletId()).toString());
        } catch (Exception ex) {
            throw new RuntimeException("Invalid UUID for outletId: " + request.getOutletId());
        }

        order.setOutletNameAtOrder(outlet.getName());
        // Placeholder: OutletDto currently doesn't have city id; use a random UUID for
        // now
        order.setOutletCityId(UUID.randomUUID().toString()); // Needs to come from OutletDto in real app
        order.setDeliveryAddressSnapshot(new DeliveryAddressSnapshot()); // Placeholder empty snapshot

        return order;
    }

    public List<OrderItem> createOrderItems(List<CreateOrderItemDto> itemRequests, Order order) {
        List<OrderItem> orderItems = new ArrayList<>();
        int lineNumber = 1;

        for (CreateOrderItemDto itemRequest : itemRequests) {
            // In a real app, you would fetch Item Price from Catalog Client here!
            // For now, assuming price is 100 for everything to test flow
            BigDecimal price = BigDecimal.valueOf(100);

            OrderItem item = new OrderItem();
            item.setOrderItemId(UUID.randomUUID().toString());
            // catalogItemId in entity is UUID -> parse from request
            try {
                if (itemRequest.getCatalogItemId() != null) {
                    item.setCatalogItemId(UUID.fromString(itemRequest.getCatalogItemId()).toString());
                }
            } catch (Exception ex) {
                throw new RuntimeException("Invalid UUID for catalogItemId: " + itemRequest.getCatalogItemId());
            }
            item.setQuantity(itemRequest.getQuantity());
            item.setSnapshotBasePrice(price);
            item.setItemsLineTotal(price.multiply(BigDecimal.valueOf(itemRequest.getQuantity())));
            item.setItemName("Item " + itemRequest.getCatalogItemId()); // Placeholder

            // Link order and logical orderId
            item.setOrder(order);
            item.setOrderId(order.getOrderId());
            item.setLineNumber(lineNumber++);

            orderItems.add(item);
        }

        return orderItems;
    }

    public OrderResponse mapToResponse(Order order) {
        OrderResponse response = new OrderResponse();
        // OrderResponse.orderId is String, Order.orderId is UUID -> convert to string
        response.setOrderId(order.getOrderId() != null ? order.getOrderId() : null);
        response.setOrderNumber(order.getOrderNumber());
        response.setStatus("CREATED"); // Hardcoded for V1
        response.setTotalAmount(order.getTotalAmount());
        response.setCreatedAt(order.getCreatedAt());
        return response;
    }

    private String generateOrderNumber() {
        return "ORD-" + System.currentTimeMillis();
    }
}
